# Generated by Django 3.1.7 on 2021-03-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210225_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='titleerror',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
