# Generated by Django 3.1.7 on 2021-03-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_titleerror_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titleerror',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
